# Generated by Django 5.2.4 on 2025-07-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('peding', 'Pendiente'), ('process', 'En Proceso'), ('fulfilled', 'Completada'), ('Rejected', 'Rechazada')], default='peding', max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
